"""
Generate 500-company registry for Sentinel.
Merges with existing 12 entries, deduplicates by domain, outputs company-registry.json.
"""
import json, re

def domain(url: str) -> str:
    return re.sub(r"^https?://(www\.)?", "", url).split("/")[0].split("?")[0]

# ── Existing 12 are preserved; additions below ──
additions = [
  # Cloud & Hosting
  {"id":"digitalocean","name":"DigitalOcean","url":"https://www.digitalocean.com","category":"cloud","tier":1},
  {"id":"linode","name":"Linode (Akamai)","url":"https://www.linode.com","category":"cloud","tier":1},
  {"id":"vultr","name":"Vultr","url":"https://www.vultr.com","category":"cloud","tier":2},
  {"id":"heroku","name":"Heroku","url":"https://www.heroku.com","category":"cloud","tier":2},
  {"id":"render","name":"Render","url":"https://render.com","category":"cloud","tier":2},
  {"id":"railway","name":"Railway","url":"https://railway.app","category":"cloud","tier":2},
  {"id":"fly-io","name":"Fly.io","url":"https://fly.io","category":"cloud","tier":2},
  {"id":"netlify","name":"Netlify","url":"https://www.netlify.com","category":"cloud","tier":1},
  {"id":"azure","name":"Microsoft Azure","url":"https://azure.microsoft.com","category":"cloud","tier":1},
  {"id":"gcp","name":"Google Cloud","url":"https://cloud.google.com","category":"cloud","tier":1},
  {"id":"oracle-cloud","name":"Oracle Cloud","url":"https://www.oracle.com/cloud","category":"cloud","tier":2},
  {"id":"ibm-cloud","name":"IBM Cloud","url":"https://www.ibm.com/cloud","category":"cloud","tier":2},
  {"id":"alibaba-cloud","name":"Alibaba Cloud","url":"https://www.alibabacloud.com","category":"cloud","tier":2},
  {"id":"hetzner","name":"Hetzner","url":"https://www.hetzner.com","category":"cloud","tier":2},
  {"id":"ovhcloud","name":"OVHcloud","url":"https://www.ovhcloud.com","category":"cloud","tier":2},
  {"id":"scaleway","name":"Scaleway","url":"https://www.scaleway.com","category":"cloud","tier":2},
  {"id":"cloudways","name":"Cloudways","url":"https://www.cloudways.com","category":"cloud","tier":2},
  {"id":"fastly","name":"Fastly","url":"https://www.fastly.com","category":"cdn","tier":1},
  {"id":"akamai","name":"Akamai","url":"https://www.akamai.com","category":"cdn","tier":1},
  {"id":"bunnycdn","name":"BunnyCDN","url":"https://bunny.net","category":"cdn","tier":2},
  {"id":"keycdn","name":"KeyCDN","url":"https://www.keycdn.com","category":"cdn","tier":2},
  # Developer Tools
  {"id":"gitlab","name":"GitLab","url":"https://gitlab.com","category":"developer","tier":1},
  {"id":"bitbucket","name":"Bitbucket","url":"https://bitbucket.org","category":"developer","tier":1},
  {"id":"npm","name":"npm Registry","url":"https://registry.npmjs.org","category":"developer","tier":1},
  {"id":"docker-hub","name":"Docker Hub","url":"https://hub.docker.com","category":"developer","tier":1},
  {"id":"circleci","name":"CircleCI","url":"https://circleci.com","category":"developer","tier":2},
  {"id":"travis-ci","name":"Travis CI","url":"https://travis-ci.com","category":"developer","tier":2},
  {"id":"jenkins","name":"Jenkins","url":"https://www.jenkins.io","category":"developer","tier":3},
  {"id":"jira","name":"Jira","url":"https://www.atlassian.com/software/jira","category":"developer","tier":1},
  {"id":"confluence","name":"Confluence","url":"https://www.atlassian.com/software/confluence","category":"developer","tier":2},
  {"id":"linear","name":"Linear","url":"https://linear.app","category":"developer","tier":2},
  {"id":"github-actions","name":"GitHub Actions","url":"https://github.com/features/actions","category":"developer","tier":1},
  {"id":"sentry","name":"Sentry","url":"https://sentry.io","category":"monitoring","tier":2},
  {"id":"codecov","name":"Codecov","url":"https://about.codecov.io","category":"developer","tier":2},
  {"id":"sonarcloud","name":"SonarCloud","url":"https://sonarcloud.io","category":"developer","tier":2},
  {"id":"snyk","name":"Snyk","url":"https://snyk.io","category":"security","tier":2},
  {"id":"dependabot","name":"Dependabot","url":"https://docs.github.com/en/code-security/dependabot","category":"security","tier":3},
  {"id":"hashicorp-vault","name":"HashiCorp Vault","url":"https://www.vaultproject.io","category":"security","tier":2},
  {"id":"1password","name":"1Password","url":"https://1password.com","category":"security","tier":2},
  {"id":"bitwarden","name":"Bitwarden","url":"https://bitwarden.com","category":"security","tier":2},
  # Payments & Fintech
  {"id":"paypal","name":"PayPal","url":"https://www.paypal.com","category":"payments","tier":1},
  {"id":"square","name":"Square","url":"https://squareup.com","category":"payments","tier":1},
  {"id":"adyen","name":"Adyen","url":"https://www.adyen.com","category":"payments","tier":1},
  {"id":"braintree","name":"Braintree","url":"https://www.braintreepayments.com","category":"payments","tier":2},
  {"id":"checkout-com","name":"Checkout.com","url":"https://www.checkout.com","category":"payments","tier":2},
  {"id":"plaid","name":"Plaid","url":"https://plaid.com","category":"fintech","tier":1},
  {"id":"wise","name":"Wise","url":"https://wise.com","category":"fintech","tier":2},
  {"id":"revolut","name":"Revolut","url":"https://www.revolut.com","category":"fintech","tier":2},
  {"id":"chime","name":"Chime","url":"https://www.chime.com","category":"fintech","tier":2},
  {"id":"robinhood","name":"Robinhood","url":"https://robinhood.com","category":"fintech","tier":2},
  {"id":"coinbase","name":"Coinbase","url":"https://www.coinbase.com","category":"crypto","tier":1},
  {"id":"binance","name":"Binance","url":"https://www.binance.com","category":"crypto","tier":1},
  {"id":"kraken","name":"Kraken","url":"https://www.kraken.com","category":"crypto","tier":2},
  {"id":"metamask","name":"MetaMask","url":"https://metamask.io","category":"crypto","tier":2},
  {"id":"lemonsqueezy","name":"Lemon Squeezy","url":"https://www.lemonsqueezy.com","category":"payments","tier":2},
  {"id":"paddle","name":"Paddle","url":"https://www.paddle.com","category":"payments","tier":2},
  {"id":"gumroad","name":"Gumroad","url":"https://gumroad.com","category":"payments","tier":2},
  {"id":"razorpay","name":"Razorpay","url":"https://razorpay.com","category":"payments","tier":2},
  # Communications & Email
  {"id":"sendgrid","name":"SendGrid","url":"https://sendgrid.com","category":"communications","tier":1},
  {"id":"mailgun","name":"Mailgun","url":"https://www.mailgun.com","category":"communications","tier":2},
  {"id":"postmark","name":"Postmark","url":"https://postmarkapp.com","category":"communications","tier":2},
  {"id":"mailchimp","name":"Mailchimp","url":"https://mailchimp.com","category":"communications","tier":1},
  {"id":"convertkit","name":"ConvertKit","url":"https://convertkit.com","category":"communications","tier":2},
  {"id":"brevo","name":"Brevo (Sendinblue)","url":"https://www.brevo.com","category":"communications","tier":2},
  {"id":"klaviyo","name":"Klaviyo","url":"https://www.klaviyo.com","category":"communications","tier":2},
  {"id":"customerio","name":"Customer.io","url":"https://customer.io","category":"communications","tier":2},
  {"id":"resend","name":"Resend","url":"https://resend.com","category":"communications","tier":2},
  {"id":"loops","name":"Loops","url":"https://loops.so","category":"communications","tier":2},
  {"id":"twilio","name":"Twilio","url":"https://www.twilio.com","category":"communications","tier":1},
  {"id":"vonage","name":"Vonage","url":"https://www.vonage.com","category":"communications","tier":2},
  {"id":"messagebird","name":"MessageBird","url":"https://www.messagebird.com","category":"communications","tier":2},
  {"id":"pusher","name":"Pusher","url":"https://pusher.com","category":"communications","tier":2},
  {"id":"ably","name":"Ably","url":"https://ably.com","category":"communications","tier":2},
  # CRM & Sales
  {"id":"salesforce","name":"Salesforce","url":"https://www.salesforce.com","category":"crm","tier":1},
  {"id":"hubspot","name":"HubSpot","url":"https://www.hubspot.com","category":"crm","tier":1},
  {"id":"pipedrive","name":"Pipedrive","url":"https://www.pipedrive.com","category":"crm","tier":2},
  {"id":"zoho-crm","name":"Zoho CRM","url":"https://www.zoho.com/crm","category":"crm","tier":2},
  {"id":"monday-com","name":"Monday.com","url":"https://monday.com","category":"crm","tier":2},
  {"id":"closeio","name":"Close","url":"https://close.com","category":"crm","tier":2},
  {"id":"apollo","name":"Apollo.io","url":"https://www.apollo.io","category":"crm","tier":2},
  {"id":"outreach","name":"Outreach","url":"https://www.outreach.io","category":"crm","tier":2},
  # Support & Customer Success
  {"id":"zendesk","name":"Zendesk","url":"https://www.zendesk.com","category":"support","tier":1},
  {"id":"intercom","name":"Intercom","url":"https://www.intercom.com","category":"support","tier":1},
  {"id":"freshdesk","name":"Freshdesk","url":"https://freshdesk.com","category":"support","tier":2},
  {"id":"helpscout","name":"Help Scout","url":"https://www.helpscout.com","category":"support","tier":2},
  {"id":"crisp","name":"Crisp","url":"https://crisp.chat","category":"support","tier":2},
  {"id":"livechat","name":"LiveChat","url":"https://www.livechat.com","category":"support","tier":2},
  {"id":"drift","name":"Drift","url":"https://www.drift.com","category":"support","tier":2},
  {"id":"tawk","name":"Tawk.to","url":"https://www.tawk.to","category":"support","tier":2},
  # Monitoring & Observability
  {"id":"datadog","name":"Datadog","url":"https://www.datadoghq.com","category":"monitoring","tier":1},
  {"id":"newrelic","name":"New Relic","url":"https://newrelic.com","category":"monitoring","tier":1},
  {"id":"grafana","name":"Grafana","url":"https://grafana.com","category":"monitoring","tier":2},
  {"id":"pagerduty","name":"PagerDuty","url":"https://www.pagerduty.com","category":"monitoring","tier":1},
  {"id":"statuspage","name":"Atlassian Statuspage","url":"https://www.atlassian.com/software/statuspage","category":"monitoring","tier":2},
  {"id":"pingdom","name":"Pingdom","url":"https://www.pingdom.com","category":"monitoring","tier":2},
  {"id":"uptimerobot","name":"UptimeRobot","url":"https://uptimerobot.com","category":"monitoring","tier":2},
  {"id":"freshping","name":"Freshping","url":"https://www.freshworks.com/website-monitoring","category":"monitoring","tier":2},
  {"id":"betterstack","name":"Better Stack","url":"https://betterstack.com","category":"monitoring","tier":2},
  {"id":"honeycomb","name":"Honeycomb","url":"https://www.honeycomb.io","category":"monitoring","tier":2},
  {"id":"lightstep","name":"Lightstep","url":"https://lightstep.com","category":"monitoring","tier":2},
  {"id":"dynatrace","name":"Dynatrace","url":"https://www.dynatrace.com","category":"monitoring","tier":1},
  # Ecommerce & Retail
  {"id":"shopify","name":"Shopify","url":"https://www.shopify.com","category":"ecommerce","tier":1},
  {"id":"bigcommerce","name":"BigCommerce","url":"https://www.bigcommerce.com","category":"ecommerce","tier":2},
  {"id":"woocommerce","name":"WooCommerce","url":"https://woocommerce.com","category":"ecommerce","tier":2},
  {"id":"magento","name":"Magento (Adobe)","url":"https://business.adobe.com/products/magento/magento-commerce.html","category":"ecommerce","tier":2},
  {"id":"amazon","name":"Amazon","url":"https://www.amazon.com","category":"ecommerce","tier":1},
  {"id":"ebay","name":"eBay","url":"https://www.ebay.com","category":"ecommerce","tier":1},
  {"id":"etsy","name":"Etsy","url":"https://www.etsy.com","category":"ecommerce","tier":1},
  {"id":"wix","name":"Wix","url":"https://www.wix.com","category":"ecommerce","tier":1},
  {"id":"squarespace","name":"Squarespace","url":"https://www.squarespace.com","category":"ecommerce","tier":1},
  {"id":"webflow","name":"Webflow","url":"https://webflow.com","category":"ecommerce","tier":2},
  {"id":"framer","name":"Framer","url":"https://www.framer.com","category":"developer","tier":2},
  {"id":"swell","name":"Swell","url":"https://www.swell.is","category":"ecommerce","tier":2},
  {"id":"medusa","name":"Medusa","url":"https://medusajs.com","category":"ecommerce","tier":2},
  # Social & Content
  {"id":"twitter-x","name":"X (Twitter)","url":"https://x.com","category":"social","tier":1},
  {"id":"facebook","name":"Facebook","url":"https://www.facebook.com","category":"social","tier":1},
  {"id":"instagram","name":"Instagram","url":"https://www.instagram.com","category":"social","tier":1},
  {"id":"linkedin","name":"LinkedIn","url":"https://www.linkedin.com","category":"social","tier":1},
  {"id":"tiktok","name":"TikTok","url":"https://www.tiktok.com","category":"social","tier":1},
  {"id":"reddit","name":"Reddit","url":"https://www.reddit.com","category":"social","tier":1},
  {"id":"discord","name":"Discord","url":"https://discord.com","category":"social","tier":1},
  {"id":"slack","name":"Slack","url":"https://slack.com","category":"communications","tier":1},
  {"id":"teams","name":"Microsoft Teams","url":"https://www.microsoft.com/en-us/microsoft-teams","category":"communications","tier":1},
  {"id":"zoom","name":"Zoom","url":"https://zoom.us","category":"communications","tier":1},
  {"id":"youtube","name":"YouTube","url":"https://www.youtube.com","category":"streaming","tier":1},
  {"id":"twitch","name":"Twitch","url":"https://www.twitch.tv","category":"streaming","tier":1},
  {"id":"spotify","name":"Spotify","url":"https://www.spotify.com","category":"streaming","tier":1},
  {"id":"netflix","name":"Netflix","url":"https://www.netflix.com","category":"streaming","tier":1},
  {"id":"apple-music","name":"Apple Music","url":"https://music.apple.com","category":"streaming","tier":1},
  {"id":"substack","name":"Substack","url":"https://substack.com","category":"social","tier":2},
  {"id":"medium","name":"Medium","url":"https://medium.com","category":"social","tier":2},
  {"id":"ghost","name":"Ghost","url":"https://ghost.org","category":"social","tier":2},
  {"id":"wordpress-com","name":"WordPress.com","url":"https://wordpress.com","category":"cms","tier":1},
  {"id":"wordpress-org","name":"WordPress.org","url":"https://wordpress.org","category":"cms","tier":2},
  {"id":"drupal","name":"Drupal","url":"https://www.drupal.org","category":"cms","tier":2},
  {"id":"contentful","name":"Contentful","url":"https://www.contentful.com","category":"cms","tier":2},
  {"id":"sanity","name":"Sanity","url":"https://www.sanity.io","category":"cms","tier":2},
  {"id":"storyblok","name":"Storyblok","url":"https://www.storyblok.com","category":"cms","tier":2},
  {"id":"prismic","name":"Prismic","url":"https://prismic.io","category":"cms","tier":2},
  # Auth & Identity
  {"id":"auth0","name":"Auth0 (Okta)","url":"https://auth0.com","category":"security","tier":1},
  {"id":"okta","name":"Okta","url":"https://www.okta.com","category":"security","tier":1},
  {"id":"firebase-auth","name":"Firebase Auth","url":"https://firebase.google.com/products/auth","category":"security","tier":1},
  {"id":"cognito","name":"AWS Cognito","url":"https://aws.amazon.com/cognito","category":"security","tier":1},
  {"id":"clerk","name":"Clerk","url":"https://clerk.com","category":"security","tier":2},
  {"id":"workos","name":"WorkOS","url":"https://workos.com","category":"security","tier":2},
  {"id":"stytch","name":"Stytch","url":"https://stytch.com","category":"security","tier":2},
  {"id":"magic-link","name":"Magic","url":"https://magic.link","category":"security","tier":2},
  # Database & Storage
  {"id":"mongodb","name":"MongoDB Atlas","url":"https://www.mongodb.com","category":"database","tier":1},
  {"id":"planetscale","name":"PlanetScale","url":"https://planetscale.com","category":"database","tier":2},
  {"id":"neon","name":"Neon","url":"https://neon.tech","category":"database","tier":2},
  {"id":"turso","name":"Turso","url":"https://turso.tech","category":"database","tier":2},
  {"id":"redis","name":"Redis Cloud","url":"https://redis.com","category":"database","tier":2},
  {"id":"upstash","name":"Upstash","url":"https://upstash.com","category":"database","tier":2},
  {"id":"fauna","name":"Fauna","url":"https://fauna.com","category":"database","tier":2},
  {"id":"cockroachdb","name":"CockroachDB","url":"https://www.cockroachlabs.com","category":"database","tier":2},
  {"id":"firebase-db","name":"Firebase (Firestore)","url":"https://firebase.google.com","category":"database","tier":1},
  {"id":"s3","name":"AWS S3","url":"https://aws.amazon.com/s3","category":"storage","tier":1},
  {"id":"r2","name":"Cloudflare R2","url":"https://www.cloudflare.com/developer-platform/r2","category":"storage","tier":2},
  {"id":"backblaze","name":"Backblaze B2","url":"https://www.backblaze.com/b2/cloud-storage.html","category":"storage","tier":2},
  {"id":"wasabi","name":"Wasabi","url":"https://wasabi.com","category":"storage","tier":2},
  {"id":"cloudinary","name":"Cloudinary","url":"https://cloudinary.com","category":"storage","tier":2},
  {"id":"imgix","name":"Imgix","url":"https://imgix.com","category":"storage","tier":2},
  # AI & ML
  {"id":"openai","name":"OpenAI","url":"https://api.openai.com","category":"ai","tier":1},
  {"id":"anthropic","name":"Anthropic","url":"https://api.anthropic.com","category":"ai","tier":1},
  {"id":"huggingface","name":"Hugging Face","url":"https://huggingface.co","category":"ai","tier":1},
  {"id":"replicate","name":"Replicate","url":"https://replicate.com","category":"ai","tier":2},
  {"id":"together-ai","name":"Together AI","url":"https://www.together.ai","category":"ai","tier":2},
  {"id":"groq","name":"Groq","url":"https://groq.com","category":"ai","tier":2},
  {"id":"perplexity","name":"Perplexity","url":"https://www.perplexity.ai","category":"ai","tier":2},
  {"id":"mistral","name":"Mistral AI","url":"https://mistral.ai","category":"ai","tier":2},
  {"id":"cohere","name":"Cohere","url":"https://cohere.com","category":"ai","tier":2},
  {"id":"elevenlabs","name":"ElevenLabs","url":"https://elevenlabs.io","category":"ai","tier":2},
  {"id":"stability-ai","name":"Stability AI","url":"https://stability.ai","category":"ai","tier":2},
  {"id":"midjourney","name":"Midjourney","url":"https://www.midjourney.com","category":"ai","tier":2},
  {"id":"runway","name":"Runway","url":"https://runwayml.com","category":"ai","tier":2},
  {"id":"pinecone","name":"Pinecone","url":"https://www.pinecone.io","category":"ai","tier":2},
  {"id":"weaviate","name":"Weaviate","url":"https://weaviate.io","category":"ai","tier":2},
  {"id":"langchain","name":"LangChain","url":"https://www.langchain.com","category":"ai","tier":2},
  # Analytics
  {"id":"google-analytics","name":"Google Analytics","url":"https://analytics.google.com","category":"analytics","tier":1},
  {"id":"mixpanel","name":"Mixpanel","url":"https://mixpanel.com","category":"analytics","tier":2},
  {"id":"amplitude","name":"Amplitude","url":"https://amplitude.com","category":"analytics","tier":2},
  {"id":"segment","name":"Segment","url":"https://segment.com","category":"analytics","tier":1},
  {"id":"posthog","name":"PostHog","url":"https://posthog.com","category":"analytics","tier":2},
  {"id":"heap","name":"Heap","url":"https://heap.io","category":"analytics","tier":2},
  {"id":"fullstory","name":"FullStory","url":"https://www.fullstory.com","category":"analytics","tier":2},
  {"id":"hotjar","name":"Hotjar","url":"https://www.hotjar.com","category":"analytics","tier":2},
  {"id":"plausible","name":"Plausible","url":"https://plausible.io","category":"analytics","tier":2},
  {"id":"fathom","name":"Fathom","url":"https://usefathom.com","category":"analytics","tier":2},
  {"id":"chartmogul","name":"ChartMogul","url":"https://chartmogul.com","category":"analytics","tier":2},
  {"id":"baremetrics","name":"Baremetrics","url":"https://baremetrics.com","category":"analytics","tier":2},
  # Productivity & Collaboration
  {"id":"notion","name":"Notion","url":"https://www.notion.so","category":"productivity","tier":1},
  {"id":"airtable","name":"Airtable","url":"https://airtable.com","category":"productivity","tier":1},
  {"id":"coda","name":"Coda","url":"https://coda.io","category":"productivity","tier":2},
  {"id":"clickup","name":"ClickUp","url":"https://clickup.com","category":"productivity","tier":2},
  {"id":"asana","name":"Asana","url":"https://asana.com","category":"productivity","tier":1},
  {"id":"trello","name":"Trello","url":"https://trello.com","category":"productivity","tier":2},
  {"id":"basecamp","name":"Basecamp","url":"https://basecamp.com","category":"productivity","tier":2},
  {"id":"todoist","name":"Todoist","url":"https://todoist.com","category":"productivity","tier":2},
  {"id":"figma","name":"Figma","url":"https://www.figma.com","category":"design","tier":1},
  {"id":"canva","name":"Canva","url":"https://www.canva.com","category":"design","tier":1},
  {"id":"miro","name":"Miro","url":"https://miro.com","category":"design","tier":2},
  {"id":"loom","name":"Loom","url":"https://www.loom.com","category":"productivity","tier":2},
  {"id":"calendly","name":"Calendly","url":"https://calendly.com","category":"productivity","tier":2},
  {"id":"cal-com","name":"Cal.com","url":"https://cal.com","category":"productivity","tier":2},
  # Search
  {"id":"algolia","name":"Algolia","url":"https://www.algolia.com","category":"search","tier":1},
  {"id":"elasticsearch","name":"Elastic","url":"https://www.elastic.co","category":"search","tier":1},
  {"id":"meilisearch","name":"Meilisearch","url":"https://www.meilisearch.com","category":"search","tier":2},
  {"id":"typesense","name":"Typesense","url":"https://typesense.org","category":"search","tier":2},
  {"id":"google-search","name":"Google Search","url":"https://www.google.com","category":"search","tier":1},
  {"id":"bing","name":"Bing","url":"https://www.bing.com","category":"search","tier":1},
  {"id":"duckduckgo","name":"DuckDuckGo","url":"https://duckduckgo.com","category":"search","tier":2},
  # DNS & Networking
  {"id":"google-dns","name":"Google DNS","url":"https://dns.google","category":"networking","tier":1},
  {"id":"cloudflare-dns","name":"Cloudflare DNS","url":"https://one.one.one.one","category":"networking","tier":1},
  {"id":"route53","name":"AWS Route53","url":"https://aws.amazon.com/route53","category":"networking","tier":1},
  {"id":"godaddy","name":"GoDaddy","url":"https://www.godaddy.com","category":"networking","tier":1},
  {"id":"namecheap","name":"Namecheap","url":"https://www.namecheap.com","category":"networking","tier":2},
  {"id":"porkbun","name":"Porkbun","url":"https://porkbun.com","category":"networking","tier":2},
  # Feature Flags & A/B Testing
  {"id":"launchdarkly","name":"LaunchDarkly","url":"https://launchdarkly.com","category":"developer","tier":2},
  {"id":"split-io","name":"Split.io","url":"https://www.split.io","category":"developer","tier":2},
  {"id":"optimizely","name":"Optimizely","url":"https://www.optimizely.com","category":"analytics","tier":2},
  {"id":"growthbook","name":"GrowthBook","url":"https://www.growthbook.io","category":"developer","tier":2},
  {"id":"statsig","name":"Statsig","url":"https://statsig.com","category":"developer","tier":2},
  {"id":"flagsmith","name":"Flagsmith","url":"https://flagsmith.com","category":"developer","tier":2},
  # Infrastructure & DevOps
  {"id":"terraform","name":"HashiCorp Terraform","url":"https://www.terraform.io","category":"devops","tier":2},
  {"id":"ansible","name":"Ansible","url":"https://www.ansible.com","category":"devops","tier":2},
  {"id":"kubernetes","name":"Kubernetes.io","url":"https://kubernetes.io","category":"devops","tier":2},
  {"id":"helm","name":"Helm","url":"https://helm.sh","category":"devops","tier":2},
  {"id":"argocd","name":"Argo CD","url":"https://argoproj.github.io/cd","category":"devops","tier":2},
  {"id":"grafana-loki","name":"Grafana Loki","url":"https://grafana.com/oss/loki","category":"monitoring","tier":2},
  {"id":"prometheus","name":"Prometheus","url":"https://prometheus.io","category":"monitoring","tier":2},
  {"id":"vector-dev","name":"Vector.dev","url":"https://vector.dev","category":"devops","tier":2},
  # HR & People Ops
  {"id":"gusto","name":"Gusto","url":"https://gusto.com","category":"hr","tier":2},
  {"id":"rippling","name":"Rippling","url":"https://www.rippling.com","category":"hr","tier":2},
  {"id":"workday","name":"Workday","url":"https://www.workday.com","category":"hr","tier":1},
  {"id":"bamboohr","name":"BambooHR","url":"https://www.bamboohr.com","category":"hr","tier":2},
  {"id":"deel","name":"Deel","url":"https://www.deel.com","category":"hr","tier":2},
  {"id":"greenhouse","name":"Greenhouse","url":"https://www.greenhouse.io","category":"hr","tier":2},
  {"id":"lever","name":"Lever","url":"https://www.lever.co","category":"hr","tier":2},
  # Legal & Compliance
  {"id":"docusign","name":"DocuSign","url":"https://www.docusign.com","category":"legal","tier":1},
  {"id":"hellosign","name":"Dropbox Sign","url":"https://sign.dropbox.com","category":"legal","tier":2},
  {"id":"ironclad","name":"Ironclad","url":"https://ironcladapp.com","category":"legal","tier":2},
  {"id":"pandadoc","name":"PandaDoc","url":"https://www.pandadoc.com","category":"legal","tier":2},
  # Misc SaaS
  {"id":"zapier","name":"Zapier","url":"https://zapier.com","category":"automation","tier":1},
  {"id":"make","name":"Make (Integromat)","url":"https://www.make.com","category":"automation","tier":2},
  {"id":"n8n","name":"n8n","url":"https://n8n.io","category":"automation","tier":2},
  {"id":"retool","name":"Retool","url":"https://retool.com","category":"developer","tier":2},
  {"id":"appsmith","name":"Appsmith","url":"https://www.appsmith.com","category":"developer","tier":2},
  {"id":"bubble","name":"Bubble","url":"https://bubble.io","category":"developer","tier":2},
  {"id":"glide","name":"Glide","url":"https://www.glideapps.com","category":"developer","tier":2},
  {"id":"typeform","name":"Typeform","url":"https://www.typeform.com","category":"productivity","tier":2},
  {"id":"surveymonkey","name":"SurveyMonkey","url":"https://www.surveymonkey.com","category":"productivity","tier":2},
  {"id":"tally","name":"Tally","url":"https://tally.so","category":"productivity","tier":2},
  {"id":"dropbox","name":"Dropbox","url":"https://www.dropbox.com","category":"storage","tier":1},
  {"id":"box","name":"Box","url":"https://www.box.com","category":"storage","tier":2},
  {"id":"onedrive","name":"OneDrive","url":"https://onedrive.live.com","category":"storage","tier":1},
  {"id":"google-drive","name":"Google Drive","url":"https://drive.google.com","category":"storage","tier":1},
  {"id":"icloud","name":"iCloud","url":"https://www.icloud.com","category":"storage","tier":1},
  # Video & Conferencing
  {"id":"livekit","name":"LiveKit","url":"https://livekit.io","category":"communications","tier":2},
  {"id":"daily","name":"Daily.co","url":"https://www.daily.co","category":"communications","tier":2},
  {"id":"agora","name":"Agora","url":"https://www.agora.io","category":"communications","tier":2},
  {"id":"whereby","name":"Whereby","url":"https://whereby.com","category":"communications","tier":2},
  {"id":"google-meet","name":"Google Meet","url":"https://meet.google.com","category":"communications","tier":1},
  {"id":"webex","name":"Cisco Webex","url":"https://www.webex.com","category":"communications","tier":2},
  # Billing & Subscriptions
  {"id":"recurly","name":"Recurly","url":"https://recurly.com","category":"payments","tier":2},
  {"id":"chargebee","name":"Chargebee","url":"https://www.chargebee.com","category":"payments","tier":2},
  {"id":"zuora","name":"Zuora","url":"https://www.zuora.com","category":"payments","tier":2},
  {"id":"chargify","name":"Chargify","url":"https://www.chargify.com","category":"payments","tier":2},
  # Map / Location
  {"id":"google-maps","name":"Google Maps","url":"https://maps.googleapis.com","category":"mapping","tier":1},
  {"id":"mapbox","name":"Mapbox","url":"https://www.mapbox.com","category":"mapping","tier":2},
  {"id":"here","name":"HERE Maps","url":"https://www.here.com","category":"mapping","tier":2},
  {"id":"openstreetmap","name":"OpenStreetMap","url":"https://www.openstreetmap.org","category":"mapping","tier":2},
  # Additional SaaS to reach 500
  {"id":"intercom-messenger","name":"Intercom Messenger","url":"https://js.intercomcdn.com","category":"support","tier":2},
  {"id":"onesignal","name":"OneSignal","url":"https://onesignal.com","category":"communications","tier":2},
  {"id":"pushwoosh","name":"Pushwoosh","url":"https://www.pushwoosh.com","category":"communications","tier":2},
  {"id":"appsflyer","name":"AppsFlyer","url":"https://www.appsflyer.com","category":"analytics","tier":2},
  {"id":"adjust","name":"Adjust","url":"https://www.adjust.com","category":"analytics","tier":2},
  {"id":"branch","name":"Branch","url":"https://www.branch.io","category":"analytics","tier":2},
  {"id":"firebase-analytics","name":"Firebase Analytics","url":"https://firebase.google.com/products/analytics","category":"analytics","tier":1},
  {"id":"clevertap","name":"CleverTap","url":"https://clevertap.com","category":"analytics","tier":2},
  {"id":"braze","name":"Braze","url":"https://www.braze.com","category":"communications","tier":2},
  {"id":"iterable","name":"Iterable","url":"https://iterable.com","category":"communications","tier":2},
  {"id":"sailthru","name":"Sailthru","url":"https://www.sailthru.com","category":"communications","tier":2},
  {"id":"sendpulse","name":"SendPulse","url":"https://sendpulse.com","category":"communications","tier":2},
  {"id":"drip","name":"Drip","url":"https://www.drip.com","category":"communications","tier":2},
  {"id":"activecampaign","name":"ActiveCampaign","url":"https://www.activecampaign.com","category":"communications","tier":1},
  {"id":"constant-contact","name":"Constant Contact","url":"https://www.constantcontact.com","category":"communications","tier":2},
  {"id":"campaign-monitor","name":"Campaign Monitor","url":"https://www.campaignmonitor.com","category":"communications","tier":2},
  {"id":"getresponse","name":"GetResponse","url":"https://www.getresponse.com","category":"communications","tier":2},
  {"id":"moosend","name":"Moosend","url":"https://moosend.com","category":"communications","tier":2},
  {"id":"omnisend","name":"Omnisend","url":"https://www.omnisend.com","category":"communications","tier":2},
  {"id":"sendlane","name":"Sendlane","url":"https://www.sendlane.com","category":"communications","tier":2},
  {"id":"emma","name":"Emma","url":"https://myemma.com","category":"communications","tier":2},
  {"id":"benchmark","name":"Benchmark Email","url":"https://www.benchmarkemail.com","category":"communications","tier":2},
  {"id":"mailerlite","name":"MailerLite","url":"https://www.mailerlite.com","category":"communications","tier":2},
  {"id":"hubspot-email","name":"HubSpot Email","url":"https://www.hubspot.com/products/marketing/email","category":"communications","tier":2},
  {"id":"pardot","name":"Salesforce Pardot","url":"https://www.salesforce.com/products/marketing-cloud/marketing-automation","category":"communications","tier":2},
  {"id":"marketo","name":"Marketo Engage","url":"https://business.adobe.com/products/marketo/adobe-marketo.html","category":"communications","tier":2},
  {"id":"eloqua","name":"Oracle Eloqua","url":"https://www.oracle.com/cx/marketing/automation","category":"communications","tier":2},
  {"id":"netcore","name":"Netcore Cloud","url":"https://netcorecloud.com","category":"communications","tier":2},
  {"id":"mailjet","name":"Mailjet","url":"https://www.mailjet.com","category":"communications","tier":2},
  {"id":"sparkpost","name":"SparkPost","url":"https://www.sparkpost.com","category":"communications","tier":2},
  {"id":"socketlabs","name":"SocketLabs","url":"https://www.socketlabs.com","category":"communications","tier":2},
  {"id":"pepipost","name":"Pepipost","url":"https://www.pepipost.com","category":"communications","tier":2},
  {"id":"elastic-email","name":"Elastic Email","url":"https://elasticemail.com","category":"communications","tier":2},
  {"id":"emailoctopus","name":"EmailOctopus","url":"https://emailoctopus.com","category":"communications","tier":2},
  {"id":"mailmodo","name":"Mailmodo","url":"https://www.mailmodo.com","category":"communications","tier":2},
  {"id":"encharge","name":"Encharge","url":"https://encharge.io","category":"communications","tier":2},
  {"id":"userlist","name":"Userlist","url":"https://userlist.com","category":"communications","tier":2},
  {"id":"vero","name":"Vero","url":"https://www.getvero.com","category":"communications","tier":2},
  {"id":"autopilot","name":"Ortto (Autopilot)","url":"https://ortto.com","category":"communications","tier":2},
  {"id":"uservoice","name":"UserVoice","url":"https://uservoice.com","category":"support","tier":2},
  {"id":"survicate","name":"Survicate","url":"https://survicate.com","category":"analytics","tier":2},
  {"id":"delighted","name":"Delighted","url":"https://delighted.com","category":"analytics","tier":2},
  {"id":"qualtrics","name":"Qualtrics","url":"https://www.qualtrics.com","category":"analytics","tier":2},
  {"id":"medallia","name":"Medallia","url":"https://www.medallia.com","category":"analytics","tier":2},
  {"id":"nicereply","name":"Nicereply","url":"https://www.nicereply.com","category":"support","tier":2},
  {"id":"satismeter","name":"Satismeter","url":"https://www.satismeter.com","category":"analytics","tier":2},
  {"id":"wootric","name":"Wootric","url":"https://wootric.com","category":"analytics","tier":2},
  {"id":"promoter","name":"Promoter.io","url":"https://www.promoter.io","category":"analytics","tier":2},
  {"id":"retently","name":"Retently","url":"https://www.retently.com","category":"analytics","tier":2},
  {"id":"asknicely","name":"AskNicely","url":"https://www.asknicely.com","category":"analytics","tier":2},
  {"id":"usersnap","name":"Usersnap","url":"https://usersnap.com","category":"support","tier":2},
  {"id":"bugsnag","name":"Bugsnag","url":"https://www.bugsnag.com","category":"monitoring","tier":2},
  {"id":"rollbar","name":"Rollbar","url":"https://rollbar.com","category":"monitoring","tier":2},
  {"id":"raygun","name":"Raygun","url":"https://raygun.com","category":"monitoring","tier":2},
  {"id":"airbrake","name":"Airbrake","url":"https://airbrake.io","category":"monitoring","tier":2},
  {"id":"logrocket","name":"LogRocket","url":"https://logrocket.com","category":"monitoring","tier":2},
  {"id":"crashlytics","name":"Firebase Crashlytics","url":"https://firebase.google.com/products/crashlytics","category":"monitoring","tier":2},
  {"id":"instabug","name":"Instabug","url":"https://www.instabug.com","category":"monitoring","tier":2},
  {"id":"sumo-logic","name":"Sumo Logic","url":"https://www.sumologic.com","category":"monitoring","tier":2},
  {"id":"splunk","name":"Splunk","url":"https://www.splunk.com","category":"monitoring","tier":1},
  {"id":"elastic-apm","name":"Elastic APM","url":"https://www.elastic.co/apm","category":"monitoring","tier":2},
  {"id":"zipkin","name":"Zipkin","url":"https://zipkin.io","category":"monitoring","tier":2},
  {"id":"jaeger","name":"Jaeger","url":"https://www.jaegertracing.io","category":"monitoring","tier":2},
  {"id":"opentelemetry","name":"OpenTelemetry","url":"https://opentelemetry.io","category":"monitoring","tier":2},
  {"id":"cloudwatch","name":"AWS CloudWatch","url":"https://aws.amazon.com/cloudwatch","category":"monitoring","tier":1},
  {"id":"stackdriver","name":"Google Cloud Monitoring","url":"https://cloud.google.com/monitoring","category":"monitoring","tier":1},
  {"id":"azure-monitor","name":"Azure Monitor","url":"https://azure.microsoft.com/en-us/products/monitor","category":"monitoring","tier":1},
  {"id":"opsgenie","name":"Opsgenie","url":"https://www.atlassian.com/software/opsgenie","category":"monitoring","tier":2},
  {"id":"victorops","name":"Splunk On-Call","url":"https://www.splunk.com/en_us/products/on-call.html","category":"monitoring","tier":2},
  {"id":"rootly","name":"Rootly","url":"https://rootly.com","category":"monitoring","tier":2},
  {"id":"incident-io","name":"Incident.io","url":"https://incident.io","category":"monitoring","tier":2},
  {"id":"firehydrant","name":"FireHydrant","url":"https://firehydrant.com","category":"monitoring","tier":2},
  {"id":"blameless","name":"Blameless","url":"https://www.blameless.com","category":"monitoring","tier":2},
  {"id":"opslevel","name":"OpsLevel","url":"https://www.opslevel.com","category":"devops","tier":2},
  {"id":"cortex","name":"Cortex","url":"https://www.cortex.io","category":"devops","tier":2},
  {"id":"backstage","name":"Spotify Backstage","url":"https://backstage.io","category":"devops","tier":2},
  {"id":"port-labs","name":"Port","url":"https://www.getport.io","category":"devops","tier":2},
  {"id":"configure8","name":"Configure8","url":"https://www.configure8.io","category":"devops","tier":2},
  {"id":"humanitec","name":"Humanitec","url":"https://humanitec.com","category":"devops","tier":2},
  {"id":"env0","name":"env0","url":"https://www.env0.com","category":"devops","tier":2},
  {"id":"spacelift","name":"Spacelift","url":"https://spacelift.io","category":"devops","tier":2},
  {"id":"atlantis","name":"Atlantis","url":"https://www.runatlantis.io","category":"devops","tier":2},
  {"id":"pulumi","name":"Pulumi","url":"https://www.pulumi.com","category":"devops","tier":2},
  {"id":"cdk","name":"AWS CDK","url":"https://aws.amazon.com/cdk","category":"devops","tier":2},
  {"id":"crossplane","name":"Crossplane","url":"https://www.crossplane.io","category":"devops","tier":2},
  {"id":"flux","name":"Flux CD","url":"https://fluxcd.io","category":"devops","tier":2},
  {"id":"tekton","name":"Tekton","url":"https://tekton.dev","category":"devops","tier":2},
  {"id":"dagger","name":"Dagger","url":"https://dagger.io","category":"devops","tier":2},
  {"id":"earthly","name":"Earthly","url":"https://earthly.dev","category":"devops","tier":2},
  {"id":"nx","name":"Nx","url":"https://nx.dev","category":"developer","tier":2},
  {"id":"turborepo","name":"Turborepo","url":"https://turbo.build","category":"developer","tier":2},
  {"id":"lerna","name":"Lerna","url":"https://lerna.js.org","category":"developer","tier":2},
  {"id":"changesets","name":"Changesets","url":"https://github.com/changesets/changesets","category":"developer","tier":2},
  {"id":"semantic-release","name":"semantic-release","url":"https://semantic-release.gitbook.io","category":"developer","tier":2},
  # More SaaS & productivity
  {"id":"xero","name":"Xero","url":"https://www.xero.com","category":"fintech","tier":2},
  {"id":"quickbooks","name":"QuickBooks Online","url":"https://quickbooks.intuit.com","category":"fintech","tier":1},
  {"id":"freshbooks","name":"FreshBooks","url":"https://www.freshbooks.com","category":"fintech","tier":2},
  {"id":"wave","name":"Wave","url":"https://www.waveapps.com","category":"fintech","tier":2},
  {"id":"bench","name":"Bench","url":"https://bench.co","category":"fintech","tier":2},
  {"id":"pilot","name":"Pilot","url":"https://pilot.com","category":"fintech","tier":2},
  {"id":"mercury","name":"Mercury","url":"https://mercury.com","category":"fintech","tier":2},
  {"id":"ramp","name":"Ramp","url":"https://ramp.com","category":"fintech","tier":2},
  {"id":"brex","name":"Brex","url":"https://www.brex.com","category":"fintech","tier":2},
  {"id":"expensify","name":"Expensify","url":"https://www.expensify.com","category":"fintech","tier":2},
  {"id":"bill-com","name":"Bill.com","url":"https://www.bill.com","category":"fintech","tier":2},
  {"id":"stripe-billing","name":"Stripe Billing","url":"https://stripe.com/billing","category":"payments","tier":1},
  {"id":"revenuecat","name":"RevenueCat","url":"https://www.revenuecat.com","category":"payments","tier":2},
  {"id":"maxio","name":"Maxio","url":"https://www.maxio.com","category":"payments","tier":2},
  {"id":"stripe-connect","name":"Stripe Connect","url":"https://stripe.com/connect","category":"payments","tier":1},
  # More developer
  {"id":"sonatype","name":"Sonatype Nexus","url":"https://www.sonatype.com","category":"developer","tier":2},
  {"id":"jfrog","name":"JFrog","url":"https://jfrog.com","category":"developer","tier":2},
  {"id":"artifactory","name":"Artifactory","url":"https://jfrog.com/artifactory","category":"developer","tier":2},
  {"id":"github-packages","name":"GitHub Packages","url":"https://github.com/features/packages","category":"developer","tier":2},
  {"id":"pypi","name":"PyPI","url":"https://pypi.org","category":"developer","tier":1},
  {"id":"rubygems","name":"RubyGems","url":"https://rubygems.org","category":"developer","tier":2},
  {"id":"packagist","name":"Packagist","url":"https://packagist.org","category":"developer","tier":2},
  {"id":"crates-io","name":"crates.io","url":"https://crates.io","category":"developer","tier":2},
  {"id":"nuget","name":"NuGet","url":"https://www.nuget.org","category":"developer","tier":2},
  {"id":"maven-central","name":"Maven Central","url":"https://repo1.maven.org","category":"developer","tier":1},
  {"id":"hex-pm","name":"Hex.pm","url":"https://hex.pm","category":"developer","tier":2},
  {"id":"hackage","name":"Hackage","url":"https://hackage.haskell.org","category":"developer","tier":2},
  {"id":"pub-dev","name":"pub.dev","url":"https://pub.dev","category":"developer","tier":2},
  {"id":"conan","name":"Conan Center","url":"https://conan.io/center","category":"developer","tier":2},
  {"id":"vcpkg","name":"vcpkg","url":"https://vcpkg.io","category":"developer","tier":2},
  # More security
  {"id":"crowdstrike","name":"CrowdStrike","url":"https://www.crowdstrike.com","category":"security","tier":1},
  {"id":"sentinelone","name":"SentinelOne","url":"https://www.sentinelone.com","category":"security","tier":1},
  {"id":"palo-alto","name":"Palo Alto Networks","url":"https://www.paloaltonetworks.com","category":"security","tier":1},
  {"id":"zscaler","name":"Zscaler","url":"https://www.zscaler.com","category":"security","tier":2},
  {"id":"qualys","name":"Qualys","url":"https://www.qualys.com","category":"security","tier":2},
  {"id":"tenable","name":"Tenable","url":"https://www.tenable.com","category":"security","tier":2},
  {"id":"rapid7","name":"Rapid7","url":"https://www.rapid7.com","category":"security","tier":2},
  {"id":"veracode","name":"Veracode","url":"https://www.veracode.com","category":"security","tier":2},
  {"id":"checkmarx","name":"Checkmarx","url":"https://checkmarx.com","category":"security","tier":2},
  {"id":"lacework","name":"Lacework","url":"https://www.lacework.com","category":"security","tier":2},
  {"id":"wiz","name":"Wiz","url":"https://www.wiz.io","category":"security","tier":2},
  {"id":"orca-security","name":"Orca Security","url":"https://orca.security","category":"security","tier":2},
  {"id":"prisma-cloud","name":"Prisma Cloud","url":"https://www.paloaltonetworks.com/prisma/cloud","category":"security","tier":2},
  {"id":"cloudtrail","name":"AWS CloudTrail","url":"https://aws.amazon.com/cloudtrail","category":"security","tier":1},
  {"id":"guardduty","name":"AWS GuardDuty","url":"https://aws.amazon.com/guardduty","category":"security","tier":1},
  # More AI
  {"id":"google-ai","name":"Google AI","url":"https://ai.google","category":"ai","tier":1},
  {"id":"deepmind","name":"Google DeepMind","url":"https://deepmind.google","category":"ai","tier":2},
  {"id":"meta-ai","name":"Meta AI","url":"https://ai.meta.com","category":"ai","tier":1},
  {"id":"xai","name":"xAI (Grok)","url":"https://x.ai","category":"ai","tier":2},
  {"id":"character-ai","name":"Character.AI","url":"https://character.ai","category":"ai","tier":2},
  {"id":"claude-ai","name":"Claude","url":"https://claude.ai","category":"ai","tier":1},
  {"id":"chatgpt","name":"ChatGPT","url":"https://chat.openai.com","category":"ai","tier":1},
  {"id":"copilot","name":"GitHub Copilot","url":"https://github.com/features/copilot","category":"ai","tier":1},
  {"id":"cursor","name":"Cursor","url":"https://www.cursor.com","category":"ai","tier":2},
  {"id":"tabnine","name":"Tabnine","url":"https://www.tabnine.com","category":"ai","tier":2},
  {"id":"codeium","name":"Codeium","url":"https://codeium.com","category":"ai","tier":2},
  {"id":"sourcegraph","name":"Sourcegraph Cody","url":"https://sourcegraph.com/cody","category":"ai","tier":2},
  {"id":"kite-ai","name":"Kite","url":"https://www.kite.com","category":"ai","tier":2},
  {"id":"mintlify","name":"Mintlify","url":"https://mintlify.com","category":"developer","tier":2},
  {"id":"docusaurus","name":"Docusaurus","url":"https://docusaurus.io","category":"developer","tier":2},
  {"id":"readme","name":"ReadMe","url":"https://readme.com","category":"developer","tier":2},
  {"id":"gitbook","name":"GitBook","url":"https://www.gitbook.com","category":"developer","tier":2},
  # More ecommerce & logistics
  {"id":"stripe-atlas","name":"Stripe Atlas","url":"https://stripe.com/atlas","category":"legal","tier":2},
  {"id":"shippo","name":"Shippo","url":"https://goshippo.com","category":"logistics","tier":2},
  {"id":"easypost","name":"EasyPost","url":"https://www.easypost.com","category":"logistics","tier":2},
  {"id":"shipbob","name":"ShipBob","url":"https://www.shipbob.com","category":"logistics","tier":2},
  {"id":"shipstation","name":"ShipStation","url":"https://www.shipstation.com","category":"logistics","tier":2},
  {"id":"fedex","name":"FedEx API","url":"https://developer.fedex.com","category":"logistics","tier":2},
  {"id":"ups","name":"UPS Developer","url":"https://developer.ups.com","category":"logistics","tier":2},
  {"id":"usps","name":"USPS Web Tools","url":"https://www.usps.com","category":"logistics","tier":2},
  {"id":"dhl","name":"DHL API","url":"https://developer.dhl.com","category":"logistics","tier":2},
  # More CMS & marketing
  {"id":"wordpress-vip","name":"WordPress VIP","url":"https://wpvip.com","category":"cms","tier":2},
  {"id":"hubspot-cms","name":"HubSpot CMS","url":"https://www.hubspot.com/products/cms","category":"cms","tier":2},
  {"id":"webflow-cms","name":"Webflow CMS","url":"https://webflow.com/cms","category":"cms","tier":2},
  {"id":"builder-io","name":"Builder.io","url":"https://www.builder.io","category":"cms","tier":2},
  {"id":"directus","name":"Directus","url":"https://directus.io","category":"cms","tier":2},
  {"id":"strapi","name":"Strapi","url":"https://strapi.io","category":"cms","tier":2},
  {"id":"keystonejs","name":"KeystoneJS","url":"https://keystonejs.com","category":"cms","tier":2},
  {"id":"payload-cms","name":"Payload CMS","url":"https://payloadcms.com","category":"cms","tier":2},
  # More productivity
  {"id":"obsidian","name":"Obsidian","url":"https://obsidian.md","category":"productivity","tier":2},
  {"id":"roam","name":"Roam Research","url":"https://roamresearch.com","category":"productivity","tier":2},
  {"id":"logseq","name":"Logseq","url":"https://logseq.com","category":"productivity","tier":2},
  {"id":"craft","name":"Craft Docs","url":"https://www.craft.do","category":"productivity","tier":2},
  {"id":"bear-app","name":"Bear","url":"https://bear.app","category":"productivity","tier":2},
  {"id":"anytype","name":"Anytype","url":"https://anytype.io","category":"productivity","tier":2},
  {"id":"fibery","name":"Fibery","url":"https://fibery.io","category":"productivity","tier":2},
  {"id":"height-app","name":"Height","url":"https://height.app","category":"productivity","tier":2},
  {"id":"plane-so","name":"Plane","url":"https://plane.so","category":"productivity","tier":2},
  {"id":"shortcut","name":"Shortcut","url":"https://www.shortcut.com","category":"developer","tier":2},
  {"id":"youtrack","name":"YouTrack","url":"https://www.jetbrains.com/youtrack","category":"developer","tier":2},
  {"id":"zenhub","name":"ZenHub","url":"https://www.zenhub.com","category":"developer","tier":2},
  {"id":"clubhouse","name":"Productboard","url":"https://www.productboard.com","category":"productivity","tier":2},
  {"id":"launchnotes","name":"LaunchNotes","url":"https://www.launchnotes.com","category":"productivity","tier":2},
  {"id":"canny","name":"Canny","url":"https://canny.io","category":"support","tier":2},
  {"id":"pendo","name":"Pendo","url":"https://www.pendo.io","category":"analytics","tier":2},
  {"id":"appcues","name":"Appcues","url":"https://www.appcues.com","category":"analytics","tier":2},
  {"id":"chameleon-so","name":"Chameleon","url":"https://www.chameleon.so","category":"analytics","tier":2},
  {"id":"userflow","name":"Userflow","url":"https://userflow.com","category":"analytics","tier":2},
  {"id":"product-fruits","name":"Product Fruits","url":"https://productfruits.com","category":"analytics","tier":2},
  {"id":"intro-js","name":"Intro.js","url":"https://introjs.com","category":"developer","tier":2},
  # Additional cloud & CDN
  {"id":"aws-lambda","name":"AWS Lambda","url":"https://aws.amazon.com/lambda","category":"cloud","tier":1},
  {"id":"gcp-functions","name":"Google Cloud Functions","url":"https://cloud.google.com/functions","category":"cloud","tier":1},
  {"id":"azure-functions","name":"Azure Functions","url":"https://azure.microsoft.com/en-us/products/functions","category":"cloud","tier":1},
  {"id":"cloudflare-workers","name":"Cloudflare Workers","url":"https://workers.cloudflare.com","category":"cloud","tier":1},
  {"id":"deno-deploy","name":"Deno Deploy","url":"https://deno.com/deploy","category":"cloud","tier":2},
  {"id":"supabase-edge","name":"Supabase Edge Functions","url":"https://supabase.com/edge-functions","category":"cloud","tier":2},
  {"id":"vercel-functions","name":"Vercel Functions","url":"https://vercel.com/docs/functions","category":"cloud","tier":2},
  {"id":"aws-ec2","name":"AWS EC2","url":"https://aws.amazon.com/ec2","category":"cloud","tier":1},
  {"id":"gcp-compute","name":"Google Compute Engine","url":"https://cloud.google.com/compute","category":"cloud","tier":1},
  {"id":"azure-vm","name":"Azure Virtual Machines","url":"https://azure.microsoft.com/en-us/products/virtual-machines","category":"cloud","tier":1},
  {"id":"aws-eks","name":"AWS EKS","url":"https://aws.amazon.com/eks","category":"cloud","tier":1},
  {"id":"gcp-gke","name":"Google GKE","url":"https://cloud.google.com/kubernetes-engine","category":"cloud","tier":1},
  {"id":"azure-aks","name":"Azure AKS","url":"https://azure.microsoft.com/en-us/products/kubernetes-service","category":"cloud","tier":1},
  {"id":"aws-rds","name":"AWS RDS","url":"https://aws.amazon.com/rds","category":"database","tier":1},
  {"id":"gcp-cloudsql","name":"Google Cloud SQL","url":"https://cloud.google.com/sql","category":"database","tier":1},
  {"id":"azure-sql","name":"Azure SQL","url":"https://azure.microsoft.com/en-us/products/azure-sql","category":"database","tier":1},
  {"id":"aws-dynamodb","name":"AWS DynamoDB","url":"https://aws.amazon.com/dynamodb","category":"database","tier":1},
  {"id":"gcp-spanner","name":"Google Cloud Spanner","url":"https://cloud.google.com/spanner","category":"database","tier":2},
  {"id":"gcp-bigquery","name":"Google BigQuery","url":"https://cloud.google.com/bigquery","category":"analytics","tier":1},
  {"id":"aws-redshift","name":"AWS Redshift","url":"https://aws.amazon.com/redshift","category":"analytics","tier":2},
  {"id":"snowflake","name":"Snowflake","url":"https://www.snowflake.com","category":"analytics","tier":1},
  {"id":"databricks","name":"Databricks","url":"https://www.databricks.com","category":"analytics","tier":1},
  {"id":"dbt-cloud","name":"dbt Cloud","url":"https://www.getdbt.com","category":"analytics","tier":2},
  {"id":"fivetran","name":"Fivetran","url":"https://www.fivetran.com","category":"analytics","tier":2},
  {"id":"stitch","name":"Stitch","url":"https://www.stitchdata.com","category":"analytics","tier":2},
  {"id":"airbyte","name":"Airbyte","url":"https://airbyte.com","category":"analytics","tier":2},
  {"id":"hightouch","name":"Hightouch","url":"https://hightouch.com","category":"analytics","tier":2},
  {"id":"census","name":"Census","url":"https://www.getcensus.com","category":"analytics","tier":2},
  {"id":"metabase","name":"Metabase","url":"https://www.metabase.com","category":"analytics","tier":2},
  {"id":"looker","name":"Looker","url":"https://cloud.google.com/looker","category":"analytics","tier":2},
  {"id":"tableau","name":"Tableau","url":"https://www.tableau.com","category":"analytics","tier":1},
  {"id":"power-bi","name":"Power BI","url":"https://powerbi.microsoft.com","category":"analytics","tier":1},
  {"id":"mode","name":"Mode Analytics","url":"https://mode.com","category":"analytics","tier":2},
  {"id":"hex","name":"Hex","url":"https://hex.tech","category":"analytics","tier":2},
  {"id":"observable","name":"Observable","url":"https://observablehq.com","category":"analytics","tier":2},
  {"id":"retool-database","name":"Retool Database","url":"https://retool.com/products/database","category":"database","tier":2},
  # Messaging & queues
  {"id":"rabbitmq","name":"RabbitMQ","url":"https://www.rabbitmq.com","category":"messaging","tier":2},
  {"id":"kafka","name":"Apache Kafka","url":"https://kafka.apache.org","category":"messaging","tier":2},
  {"id":"confluent","name":"Confluent","url":"https://www.confluent.io","category":"messaging","tier":2},
  {"id":"aws-sqs","name":"AWS SQS","url":"https://aws.amazon.com/sqs","category":"messaging","tier":1},
  {"id":"aws-sns","name":"AWS SNS","url":"https://aws.amazon.com/sns","category":"messaging","tier":1},
  {"id":"gcp-pubsub","name":"Google Cloud Pub/Sub","url":"https://cloud.google.com/pubsub","category":"messaging","tier":1},
  {"id":"azure-servicebus","name":"Azure Service Bus","url":"https://azure.microsoft.com/en-us/products/service-bus","category":"messaging","tier":1},
  {"id":"nats","name":"NATS","url":"https://nats.io","category":"messaging","tier":2},
  {"id":"inngest","name":"Inngest","url":"https://www.inngest.com","category":"messaging","tier":2},
  {"id":"trigger-dev","name":"Trigger.dev","url":"https://trigger.dev","category":"messaging","tier":2},
  {"id":"temporal","name":"Temporal","url":"https://temporal.io","category":"messaging","tier":2},
  {"id":"conductor","name":"Conductor","url":"https://conductor.netflix.com","category":"messaging","tier":2},
  {"id":"dagster","name":"Dagster","url":"https://dagster.io","category":"devops","tier":2},
  {"id":"airflow","name":"Apache Airflow","url":"https://airflow.apache.org","category":"devops","tier":2},
  {"id":"prefect","name":"Prefect","url":"https://www.prefect.io","category":"devops","tier":2},
  # Final batch to reach 500
  {"id":"stripe-radar","name":"Stripe Radar","url":"https://stripe.com/radar","category":"security","tier":2},
  {"id":"veriff","name":"Veriff","url":"https://www.veriff.com","category":"security","tier":2},
  {"id":"onfido","name":"Onfido","url":"https://onfido.com","category":"security","tier":2},
  {"id":"persona","name":"Persona","url":"https://withpersona.com","category":"security","tier":2},
  {"id":"sardine","name":"Sardine","url":"https://www.sardine.ai","category":"security","tier":2},
  {"id":"sift","name":"Sift","url":"https://sift.com","category":"security","tier":2},
  {"id":"kount","name":"Kount","url":"https://kount.com","category":"security","tier":2},
  {"id":"signalwire","name":"SignalWire","url":"https://signalwire.com","category":"communications","tier":2},
  {"id":"bandwidth","name":"Bandwidth","url":"https://www.bandwidth.com","category":"communications","tier":2},
  {"id":"telnyx","name":"Telnyx","url":"https://telnyx.com","category":"communications","tier":2},
  {"id":"plivo","name":"Plivo","url":"https://www.plivo.com","category":"communications","tier":2},
  {"id":"sinch","name":"Sinch","url":"https://www.sinch.com","category":"communications","tier":2},
  {"id":"infobip","name":"Infobip","url":"https://www.infobip.com","category":"communications","tier":2},
  {"id":"bird-cx","name":"Bird (MessageBird)","url":"https://bird.com","category":"communications","tier":2},
  {"id":"clicksend","name":"ClickSend","url":"https://www.clicksend.com","category":"communications","tier":2},
  {"id":"attio","name":"Attio","url":"https://attio.com","category":"crm","tier":2},
  {"id":"folk","name":"Folk","url":"https://www.folk.app","category":"crm","tier":2},
  {"id":"affinity","name":"Affinity","url":"https://www.affinity.co","category":"crm","tier":2},
  {"id":"clay","name":"Clay","url":"https://www.clay.com","category":"crm","tier":2},
  {"id":"instantly","name":"Instantly","url":"https://instantly.ai","category":"crm","tier":2},
  {"id":"smartlead","name":"Smartlead","url":"https://smartlead.ai","category":"crm","tier":2},
  {"id":"lemlist","name":"Lemlist","url":"https://lemlist.com","category":"crm","tier":2},
  {"id":"reply-io","name":"Reply.io","url":"https://reply.io","category":"crm","tier":2},
  {"id":"salesloft","name":"Salesloft","url":"https://www.salesloft.com","category":"crm","tier":2},
  {"id":"gong","name":"Gong","url":"https://www.gong.io","category":"crm","tier":2},
  {"id":"chorus","name":"Chorus.ai","url":"https://www.chorus.ai","category":"crm","tier":2},
  {"id":"loom-video","name":"Loom Video","url":"https://www.loom.com/share","category":"productivity","tier":2},
  {"id":"descript","name":"Descript","url":"https://www.descript.com","category":"productivity","tier":2},
  {"id":"riverside","name":"Riverside.fm","url":"https://riverside.fm","category":"productivity","tier":2},
  {"id":"squadcast","name":"Squadcast","url":"https://squadcast.fm","category":"productivity","tier":2},
  {"id":"buzzsprout","name":"Buzzsprout","url":"https://www.buzzsprout.com","category":"productivity","tier":2},
  {"id":"transistor","name":"Transistor.fm","url":"https://transistor.fm","category":"productivity","tier":2},
  {"id":"simplecast","name":"Simplecast","url":"https://www.simplecast.com","category":"productivity","tier":2},
  {"id":"captivate","name":"Captivate","url":"https://www.captivate.fm","category":"productivity","tier":2},
  {"id":"podbean","name":"Podbean","url":"https://www.podbean.com","category":"productivity","tier":2},
  {"id":"castos","name":"Castos","url":"https://castos.com","category":"productivity","tier":2},
  {"id":"anchor","name":"Anchor (Spotify)","url":"https://anchor.fm","category":"streaming","tier":2},
  {"id":"libsyn","name":"Libsyn","url":"https://libsyn.com","category":"streaming","tier":2},
  {"id":"megaphone","name":"Megaphone","url":"https://megaphone.fm","category":"streaming","tier":2},
  {"id":"acast","name":"Acast","url":"https://www.acast.com","category":"streaming","tier":2},
  {"id":"spreaker","name":"Spreaker","url":"https://www.spreaker.com","category":"streaming","tier":2},
  {"id":"audiomack","name":"Audiomack","url":"https://audiomack.com","category":"streaming","tier":2},
  {"id":"soundcloud","name":"SoundCloud","url":"https://soundcloud.com","category":"streaming","tier":2},
  {"id":"bandcamp","name":"Bandcamp","url":"https://bandcamp.com","category":"streaming","tier":2},
]

# Load existing
with open(r'C:\Users\aep11\OneDrive\Git\Sentinel\GitHub\sentinel-master\company-registry.json') as f:
    existing = json.load(f)

seen_domains = set()
merged = []

for c in existing:
    d = domain(c['url'])
    if d not in seen_domains:
        seen_domains.add(d)
        c.setdefault('logo_url', f'https://logo.clearbit.com/{d}')
        merged.append(c)

for c in additions:
    d = domain(c['url'])
    if d not in seen_domains:
        seen_domains.add(d)
        c['logo_url'] = f'https://logo.clearbit.com/{d}'
        merged.append(c)

print(f'Total after dedup: {len(merged)}')
# Show breakdown by category
from collections import Counter
cats = Counter(c['category'] for c in merged)
for k, v in sorted(cats.items(), key=lambda x: -x[1]):
    print(f'  {k}: {v}')

with open(r'C:\Users\aep11\OneDrive\Git\Sentinel\GitHub\sentinel-master\company-registry.json', 'w') as f:
    json.dump(merged, f, indent=2)

print('Written.')
